#ifndef TOKEN_TICKER_APP_RUNTIME_MODE_H
#define TOKEN_TICKER_APP_RUNTIME_MODE_H

typedef enum
{
    APP_RUNTIME_MODE_SCHEDULED_ACTIVE = 0,
    APP_RUNTIME_MODE_SCHEDULED_SLEEP,
    APP_RUNTIME_MODE_WAKING,
    APP_RUNTIME_MODE_MANUAL_ACTIVE_OVERRIDE,
} app_runtime_mode_t;

#endif